- name: Config Time Server
  hosts: all
  gather_facts: no
  vars:
    - timeserver1: "1.th.pool.ntp.org"
    - timeserver2: "asia.pool.ntp.org"
  tasks:
   - name: make sure chronyd is installed
     yum:
       name: chrony
       state: latest
       update_cache: yes
   - name: deploy chrony.conf template
     template:
       src: chrony.conf.j2
       dest: /etc/chrony.conf
       owner: root
       group: root
       mode: 0644
       backup: yes
   - name: Restart chronyd
     service:
       name: chronyd
       state: restarted
   - name: Set timezone to Asia/Bangkok
     community.general.timezone:
       name: Asia/Bangkok
